<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media/v1/media.proto

namespace App\Media\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>media.v1.DirectoriesResponse</code>
 */
class DirectoriesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string names = 1 [json_name = "names"];</code>
     */
    private $names;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $names
     * }
     */
    public function __construct($data = NULL) {
        \App\Media\Grpc\GPBMetadata\Media::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string names = 1 [json_name = "names"];</code>
     * @return RepeatedField<string>
     */
    public function getNames()
    {
        return $this->names;
    }

    /**
     * Generated from protobuf field <code>repeated string names = 1 [json_name = "names"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setNames(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->names = $arr;

        return $this;
    }

}

