<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media/v1/media.proto

namespace App\Media\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>media.v1.GenerateThumbnailsRequest</code>
 */
class GenerateThumbnailsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string source_key = 1 [json_name = "sourceKey"];</code>
     */
    protected $source_key = '';
    /**
     * e.g. "webp"
     *
     * Generated from protobuf field <code>string format = 2 [json_name = "format"];</code>
     */
    protected $format = '';
    /**
     * encoder quality, e.g. 80
     *
     * Generated from protobuf field <code>uint32 quality = 3 [json_name = "quality"];</code>
     */
    protected $quality = 0;
    /**
     * Generated from protobuf field <code>repeated .media.v1.ThumbnailSpec specs = 4 [json_name = "specs"];</code>
     */
    private $specs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source_key
     *     @type string $format
     *           e.g. "webp"
     *     @type int $quality
     *           encoder quality, e.g. 80
     *     @type \App\Media\Grpc\ThumbnailSpec[] $specs
     * }
     */
    public function __construct($data = NULL) {
        \App\Media\Grpc\GPBMetadata\Media::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string source_key = 1 [json_name = "sourceKey"];</code>
     * @return string
     */
    public function getSourceKey()
    {
        return $this->source_key;
    }

    /**
     * Generated from protobuf field <code>string source_key = 1 [json_name = "sourceKey"];</code>
     * @param string $var
     * @return $this
     */
    public function setSourceKey(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->source_key = $var;

        return $this;
    }

    /**
     * e.g. "webp"
     *
     * Generated from protobuf field <code>string format = 2 [json_name = "format"];</code>
     * @return string
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * e.g. "webp"
     *
     * Generated from protobuf field <code>string format = 2 [json_name = "format"];</code>
     * @param string $var
     * @return $this
     */
    public function setFormat(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->format = $var;

        return $this;
    }

    /**
     * encoder quality, e.g. 80
     *
     * Generated from protobuf field <code>uint32 quality = 3 [json_name = "quality"];</code>
     * @return int
     */
    public function getQuality()
    {
        return $this->quality;
    }

    /**
     * encoder quality, e.g. 80
     *
     * Generated from protobuf field <code>uint32 quality = 3 [json_name = "quality"];</code>
     * @param int $var
     * @return $this
     */
    public function setQuality(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->quality = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .media.v1.ThumbnailSpec specs = 4 [json_name = "specs"];</code>
     * @return RepeatedField<\App\Media\Grpc\ThumbnailSpec>
     */
    public function getSpecs()
    {
        return $this->specs;
    }

    /**
     * Generated from protobuf field <code>repeated .media.v1.ThumbnailSpec specs = 4 [json_name = "specs"];</code>
     * @param \App\Media\Grpc\ThumbnailSpec[] $var
     * @return $this
     */
    public function setSpecs(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Media\Grpc\ThumbnailSpec::class);
        $this->specs = $arr;

        return $this;
    }

}

