<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media/v1/media.proto

namespace App\Media\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>media.v1.GenerateThumbnailsResponse</code>
 */
class GenerateThumbnailsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .media.v1.Thumbnail thumbnails = 1 [json_name = "thumbnails"];</code>
     */
    private $thumbnails;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Media\Grpc\Thumbnail[] $thumbnails
     * }
     */
    public function __construct($data = NULL) {
        \App\Media\Grpc\GPBMetadata\Media::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .media.v1.Thumbnail thumbnails = 1 [json_name = "thumbnails"];</code>
     * @return RepeatedField<\App\Media\Grpc\Thumbnail>
     */
    public function getThumbnails()
    {
        return $this->thumbnails;
    }

    /**
     * Generated from protobuf field <code>repeated .media.v1.Thumbnail thumbnails = 1 [json_name = "thumbnails"];</code>
     * @param \App\Media\Grpc\Thumbnail[] $var
     * @return $this
     */
    public function setThumbnails(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Media\Grpc\Thumbnail::class);
        $this->thumbnails = $arr;

        return $this;
    }

}

