<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media/v1/media.proto

namespace App\Media\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>media.v1.MoveRequest</code>
 */
class MoveRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string source = 1 [json_name = "source"];</code>
     */
    protected $source = '';
    /**
     * Generated from protobuf field <code>string destination = 2 [json_name = "destination"];</code>
     */
    protected $destination = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source
     *     @type string $destination
     * }
     */
    public function __construct($data = NULL) {
        \App\Media\Grpc\GPBMetadata\Media::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string source = 1 [json_name = "source"];</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Generated from protobuf field <code>string source = 1 [json_name = "source"];</code>
     * @param string $var
     * @return $this
     */
    public function setSource(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string destination = 2 [json_name = "destination"];</code>
     * @return string
     */
    public function getDestination()
    {
        return $this->destination;
    }

    /**
     * Generated from protobuf field <code>string destination = 2 [json_name = "destination"];</code>
     * @param string $var
     * @return $this
     */
    public function setDestination(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->destination = $var;

        return $this;
    }

}

