<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media/v1/media.proto

namespace App\Media\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>media.v1.ReadResponse</code>
 */
class ReadResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes chunk = 1 [json_name = "chunk"];</code>
     */
    protected $chunk = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $chunk
     * }
     */
    public function __construct($data = NULL) {
        \App\Media\Grpc\GPBMetadata\Media::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes chunk = 1 [json_name = "chunk"];</code>
     * @return string
     */
    public function getChunk()
    {
        return $this->chunk;
    }

    /**
     * Generated from protobuf field <code>bytes chunk = 1 [json_name = "chunk"];</code>
     * @param string $var
     * @return $this
     */
    public function setChunk(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->chunk = $var;

        return $this;
    }

}

