<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media/v1/media.proto

namespace App\Media\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * ThumbnailSpec describes ONE variant to generate: the target aspect ratio
 * (aspect_w:aspect_h) and the width of the output. Height is derived as
 * width * aspect_h / aspect_w. The source is crop-to-filled (centered) to that
 * ratio before resizing.
 *
 * Generated from protobuf message <code>media.v1.ThumbnailSpec</code>
 */
class ThumbnailSpec extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 aspect_w = 1 [json_name = "aspectW"];</code>
     */
    protected $aspect_w = 0;
    /**
     * Generated from protobuf field <code>uint32 aspect_h = 2 [json_name = "aspectH"];</code>
     */
    protected $aspect_h = 0;
    /**
     * Generated from protobuf field <code>uint32 width = 3 [json_name = "width"];</code>
     */
    protected $width = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $aspect_w
     *     @type int $aspect_h
     *     @type int $width
     * }
     */
    public function __construct($data = NULL) {
        \App\Media\Grpc\GPBMetadata\Media::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 aspect_w = 1 [json_name = "aspectW"];</code>
     * @return int
     */
    public function getAspectW()
    {
        return $this->aspect_w;
    }

    /**
     * Generated from protobuf field <code>uint32 aspect_w = 1 [json_name = "aspectW"];</code>
     * @param int $var
     * @return $this
     */
    public function setAspectW(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->aspect_w = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 aspect_h = 2 [json_name = "aspectH"];</code>
     * @return int
     */
    public function getAspectH()
    {
        return $this->aspect_h;
    }

    /**
     * Generated from protobuf field <code>uint32 aspect_h = 2 [json_name = "aspectH"];</code>
     * @param int $var
     * @return $this
     */
    public function setAspectH(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->aspect_h = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 width = 3 [json_name = "width"];</code>
     * @return int
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * Generated from protobuf field <code>uint32 width = 3 [json_name = "width"];</code>
     * @param int $var
     * @return $this
     */
    public function setWidth(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->width = $var;

        return $this;
    }

}

