<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Seed the catalog with the default top-level eBook categories, so the publish
 * form has something to pick from. Data migration (reference data), safe to
 * re-run: ids are generated by the DB and rows are keyed by their unique slug
 * (ON CONFLICT DO NOTHING). Ordering in the UI is driven by `position`.
 */
final class Version20260722180000 extends AbstractMigration
{
    /** @var array<int, array{0: string, 1: string}> position => [name, slug] */
    private const array CATEGORIES = [
        10 => ['Kryminał, sensacja i thriller', 'kryminal-sensacja-thriller'],
        20 => ['Fantastyka i science fiction', 'fantastyka-science-fiction'],
        30 => ['Romans i literatura obyczajowa', 'romans-literatura-obyczajowa'],
        40 => ['Literatura piękna', 'literatura-piekna'],
        50 => ['Horror i groza', 'horror-groza'],
        60 => ['Biznes i ekonomia', 'biznes-ekonomia'],
        70 => ['Rozwój osobisty', 'rozwoj-osobisty'],
        80 => ['Informatyka i technologie', 'informatyka-technologie'],
        90 => ['Nauka i edukacja', 'nauka-edukacja'],
        100 => ['Historia', 'historia'],
        110 => ['Biografie i reportaż', 'biografie-reportaz'],
        120 => ['Dla dzieci', 'dla-dzieci'],
        130 => ['Młodzieżowe (Young Adult)', 'mlodziezowe-young-adult'],
        140 => ['Poradniki', 'poradniki'],
        150 => ['Zdrowie i uroda', 'zdrowie-uroda'],
        160 => ['Kuchnia i kulinaria', 'kuchnia-kulinaria'],
        170 => ['Podróże', 'podroze'],
        180 => ['Religia i duchowość', 'religia-duchowosc'],
        190 => ['Hobby i czas wolny', 'hobby-czas-wolny'],
        200 => ['Komiks i manga', 'komiks-manga'],
    ];

    public function getDescription(): string
    {
        return 'Seed default top-level eBook categories.';
    }

    public function up(Schema $schema): void
    {
        foreach (self::CATEGORIES as $position => [$name, $slug]) {
            $this->addSql(
                'INSERT INTO categories (id, name, slug, position, created_at) '
                . 'VALUES (gen_random_uuid(), :name, :slug, :position, now()) '
                . 'ON CONFLICT (slug) DO NOTHING',
                ['name' => $name, 'slug' => $slug, 'position' => $position],
            );
        }
    }

    public function down(Schema $schema): void
    {
        $slugs = array_map(static fn (array $c): string => $c[1], self::CATEGORIES);
        // eBooks referencing these have category_id set to NULL (ON DELETE SET NULL).
        $this->addSql(
            'DELETE FROM categories WHERE slug IN (:slugs)',
            ['slugs' => $slugs],
            ['slugs' => \Doctrine\DBAL\ArrayParameterType::STRING],
        );
    }
}
